# Generated by Django 5.1.15 on 2026-05-23 19:15

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('product', 'Finished product'), ('raw_material', 'Raw material')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='catalog.product')),
                ('raw_material', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='catalog.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('purchase', 'Purchase (raw material received)'), ('production_in', 'Production output'), ('production_out', 'Production consumption'), ('sale', 'Sale'), ('adjustment_in', 'Manual adjustment (in)'), ('adjustment_out', 'Manual adjustment (out)'), ('waste', 'Waste / loss'), ('return', 'Customer return')], max_length=20)),
                ('quantity_delta', models.DecimalField(decimal_places=4, help_text='Signed change. Positive = added; negative = removed.', max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=4, max_digits=14)),
                ('reference', models.CharField(blank=True, help_text='Free-text reference: invoice number, run id, etc.', max_length=160)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stockitem',
            index=models.Index(fields=['kind'], name='inventory_s_kind_4fef19_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'product'), ('product__isnull', False), ('raw_material__isnull', True)), models.Q(('kind', 'raw_material'), ('product__isnull', True), ('raw_material__isnull', False)), _connector='OR'), name='stock_item_one_target'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['stock_item', '-created_at'], name='inventory_s_stock_i_73796c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reason', '-created_at'], name='inventory_s_reason_748aca_idx'),
        ),
    ]
