import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Menu, LogOut, User as UserIcon } from 'lucide-react';
import { useState } from 'react';
import { useAuth } from '@/store/AuthContext';
export function Topbar({ onMenu }) {
    const { user, logout } = useAuth();
    const [open, setOpen] = useState(false);
    return (_jsx("header", { className: "sticky top-0 z-30 bg-white/80 backdrop-blur border-b border-slate-200", children: _jsxs("div", { className: "flex items-center justify-between h-16 px-4 sm:px-6", children: [_jsx("button", { onClick: onMenu, className: "lg:hidden text-slate-600", children: _jsx(Menu, { size: 22 }) }), _jsx("div", { className: "flex-1" }), _jsxs("div", { className: "relative", children: [_jsxs("button", { onClick: () => setOpen((v) => !v), className: "flex items-center gap-2 px-2 py-1.5 rounded-md hover:bg-slate-100", children: [_jsx("div", { className: "h-8 w-8 rounded-full bg-brand-500 text-white text-xs font-semibold flex items-center justify-center", children: (user?.full_name ?? 'U').split(' ').map((w) => w[0]).slice(0, 2).join('') }), _jsxs("div", { className: "text-left hidden sm:block", children: [_jsx("p", { className: "text-sm font-medium text-slate-900 leading-tight", children: user?.full_name }), _jsx("p", { className: "text-xs text-slate-500 capitalize", children: user?.role })] })] }), open && (_jsx("div", { onClick: () => setOpen(false), className: "fixed inset-0 z-40" })), open && (_jsxs("div", { className: "absolute right-0 mt-2 w-56 bg-white rounded-md shadow-lg border border-slate-200 py-1 z-50", children: [_jsxs("div", { className: "px-3 py-2 border-b border-slate-100", children: [_jsx("p", { className: "text-sm font-medium", children: user?.full_name }), _jsx("p", { className: "text-xs text-slate-500 truncate", children: user?.email })] }), _jsxs("button", { className: "flex w-full items-center gap-2 px-3 py-2 text-sm text-slate-700 hover:bg-slate-50", children: [_jsx(UserIcon, { size: 16 }), " Profile"] }), _jsxs("button", { onClick: logout, className: "flex w-full items-center gap-2 px-3 py-2 text-sm text-red-600 hover:bg-red-50", children: [_jsx(LogOut, { size: 16 }), " Sign out"] })] }))] })] }) }));
}
