# Generated by Django 5.1.15 on 2026-06-01 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_asset'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='asset',
            new_name='finance_ass_purchas_4dd2d2_idx',
            old_name='finance_ass_purchas_idx',
        ),
        migrations.RenameIndex(
            model_name='asset',
            new_name='finance_ass_categor_592c2a_idx',
            old_name='finance_ass_categor_idx',
        ),
        migrations.RenameIndex(
            model_name='asset',
            new_name='finance_ass_status_4b55be_idx',
            old_name='finance_ass_status_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='finance_tra_occurre_b1b473_idx',
            old_name='finance_tx_occurre_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='finance_tra_directi_fa6c02_idx',
            old_name='finance_tx_directi_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='finance_tra_categor_06bfda_idx',
            old_name='finance_tx_categor_idx',
        ),
    ]
