# Generated by Django 5.1.15 on 2026-06-11 09:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_rename_finance_ass_purchas_idx_finance_ass_purchas_4dd2d2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('account_type', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank', 'Bank Account'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=16)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Balance on the day this wallet started being tracked.', max_digits=14)),
                ('institution', models.CharField(blank=True, help_text="Bank or provider name, e.g. 'Bank of Kigali', 'MTN MoMo'.", max_length=120)),
                ('account_number', models.CharField(blank=True, help_text='Account number or phone line — store masked if sensitive.', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WalletEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer_in', 'Transfer in'), ('transfer_out', 'Transfer out')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('occurred_on', models.DateField(default=django.utils.timezone.localdate)),
                ('description', models.CharField(blank=True, max_length=160)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('transfer_group', models.UUIDField(blank=True, db_index=True, help_text='Shared by the two rows of a single transfer.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('counterparty_wallet', models.ForeignKey(blank=True, help_text='The other wallet involved, for transfers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counterparty_entries', to='finance.wallet')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_entries', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='finance.wallet')),
            ],
            options={
                'verbose_name_plural': 'wallet entries',
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['account_type'], name='finance_wal_account_162f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['is_active'], name='finance_wal_is_acti_15a83a_idx'),
        ),
        migrations.AddIndex(
            model_name='walletentry',
            index=models.Index(fields=['wallet', '-occurred_on'], name='finance_wal_wallet__bb9142_idx'),
        ),
        migrations.AddIndex(
            model_name='walletentry',
            index=models.Index(fields=['entry_type'], name='finance_wal_entry_t_d60c36_idx'),
        ),
    ]
