# Generated by Django 5.1.15 on 2026-06-11 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_wallet_walletentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='wallet',
            field=models.ForeignKey(blank=True, help_text="Wallet the money was paid out of. Drives that wallet's balance.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(blank=True, help_text="Wallet the money moved through. Drives that wallet's balance.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.wallet'),
        ),
    ]
