# Generated by Django 5.1.15 on 2026-07-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_expense_wallet_transaction_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='on_credit',
            field=models.BooleanField(default=False, help_text='Supplier bill bought on credit: the expense is recognized now but credits Accounts Payable instead of a wallet until it is settled.'),
        ),
        migrations.AddField(
            model_name='expense',
            name='settled_at',
            field=models.DateField(blank=True, help_text='When an on-credit bill was paid. Drives the A/P settlement entry.', null=True),
        ),
    ]
