# Generated by Django 5.1.15 on 2026-05-23 19:13

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'product categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('unit', models.CharField(choices=[('g', 'Gram (g)'), ('kg', 'Kilogram (kg)'), ('ml', 'Milliliter (ml)'), ('l', 'Liter (l)'), ('unit', 'Unit'), ('dozen', 'Dozen'), ('pack', 'Pack')], max_length=10)),
                ('unit_cost', models.DecimalField(decimal_places=4, help_text='Cost per single unit (e.g. per gram, per ml, per egg).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reorder_threshold', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Alert when on-hand quantity falls to or below this.', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('g', 'Gram (g)'), ('kg', 'Kilogram (kg)'), ('ml', 'Milliliter (ml)'), ('l', 'Liter (l)'), ('unit', 'Unit'), ('dozen', 'Dozen'), ('pack', 'Pack')], default='unit', max_length=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('production_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Derived/estimated cost to produce one unit.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reorder_threshold', models.PositiveIntegerField(default=10, help_text='Trigger a low-stock alert when on-hand falls to or below this.')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.productcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Quantity of the raw material needed for ONE unit of the product.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='catalog.product')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='catalog.rawmaterial')),
            ],
            options={
                'ordering': ['product', 'raw_material'],
            },
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='preferred_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_materials', to='catalog.supplier'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='catalog_pro_categor_891fe8_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipeitem',
            constraint=models.UniqueConstraint(fields=('product', 'raw_material'), name='unique_product_raw_material'),
        ),
    ]
