# Generated by Django 5.1.15 on 2026-07-09 14:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0006_expense_wallet_transaction_wallet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(help_text='First day of the month.', unique=True)),
                ('label', models.CharField(help_text="e.g. '2026-07'.", max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('locked', 'Locked')], default='open', max_length=8)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=12)),
                ('subtype', models.CharField(blank=True, help_text="Free-form grouping, e.g. 'current_asset', 'cogs', 'operating_expense'.", max_length=40)),
                ('is_postable', models.BooleanField(default=True, help_text='Only leaf accounts may receive journal lines.')),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.CharField(default='RWF', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('expense_category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_account', to='finance.expensecategory')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='ledger.account')),
                ('wallet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_account', to='finance.wallet')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.localdate, help_text='Accounting date — when the event is recognized, not created_at.')),
                ('memo', models.CharField(blank=True, max_length=240)),
                ('source_type', models.CharField(blank=True, help_text="Domain model label, e.g. 'sales.Sale'. Blank for manual entries.", max_length=40)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('event', models.CharField(blank=True, help_text="Distinguishes multiple entries per source, e.g. 'revenue', 'cogs'.", max_length=40)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('reversed', 'Reversed')], default='posted', max_length=10)),
                ('is_system', models.BooleanField(default=True, help_text='Auto-posted from a domain event vs. entered by hand.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.accountingperiod')),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by_entries', to='ledger.journalentry')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('memo', models.CharField(blank=True, max_length=240)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='ledger.account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ledger.journalentry')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_lines', to='finance.wallet')),
            ],
            options={
                'ordering': ['entry', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['type'], name='ledger_acco_type_cdd804_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_active'], name='ledger_acco_is_acti_9d2d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['-date'], name='ledger_jour_date_c442f1_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['source_type', 'source_id'], name='ledger_jour_source__23ab73_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['status'], name='ledger_jour_status_ca98fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'posted'), models.Q(('source_type', ''), _negated=True)), fields=('source_type', 'source_id', 'event'), name='unique_live_entry_per_source_event'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['account'], name='ledger_jour_account_b1e25f_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('debit', Decimal('0')), ('credit', Decimal('0')), _connector='OR'), name='journal_line_one_side_only'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', Decimal('0')), ('credit__gte', Decimal('0'))), name='journal_line_non_negative'),
        ),
    ]
