# Generated by Django 5.1.15 on 2026-07-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(blank=True, help_text="Domain model label, e.g. 'sales.Sale'. Blank for manual entries.", max_length=64),
        ),
    ]
