# Generated by Django 5.1.15 on 2026-06-01 08:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processed_materials', '0003_recursive_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedmaterial',
            name='reorder_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Alert when on-hand falls to or below this.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='processedmaterial',
            name='shelf_life_hours',
            field=models.PositiveIntegerField(default=24, help_text='Hours the processed material remains usable after preparation.'),
        ),
        migrations.AlterField(
            model_name='processedmaterial',
            name='yield_per_batch',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Units produced by one standard batch.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='processedmaterialbatch',
            name='batches',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='How many standard batches to run (each yields yield_per_batch).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='processedmaterialbatch',
            name='quantity_produced',
            field=models.DecimalField(decimal_places=4, help_text='Total units produced = batches × yield_per_batch.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='processedmaterialrecipeitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, help_text='Quantity of the ingredient needed for ONE batch.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AlterField(
            model_name='productprocessedmaterialusage',
            name='quantity',
            field=models.DecimalField(decimal_places=4, help_text='Amount of processed material per ONE product unit.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
    ]
