# Generated by Django 5.1.15 on 2026-06-11 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_expense_wallet_transaction_wallet'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='wallet',
            field=models.ForeignKey(blank=True, help_text="Wallet the takings landed in. Drives that wallet's balance.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='finance.wallet'),
        ),
    ]
